# pylint: disable=C0103
# Generated by Django 3.2.9 on 2021-11-26 12:04
"""
Models Migrations in DB
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    """
    Migrations
    """
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True
                    )),
                (
                    'emp_name',
                    models.CharField(max_length=200
                                     )),
                (
                    'mobile',
                    phonenumber_field.modelfields.PhoneNumberField(
                        default='+12125552369',
                        max_length=128,
                        region=None,
                        unique=True
                    )),
                (
                    'emp_code',
                    models.IntegerField(
                        default=0,
                        unique=True
                    )),
                (
                    'position',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='todo_app.position'
                    )),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='parent_user',
                        to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
